name: multilogin2
description: "Another trial for various login methods."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.0.0" # Ensure compatibility with Flutter version

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.6
  google_sign_in: ^6.2.1
  http: ^1.2.0
  flutter_facebook_auth: ^6.1.1
  provider: ^6.1.2
  cloud_firestore: ^4.15.6
  shared_preferences: ^2.2.3
  font_awesome_flutter: ^10.7.0
  rounded_loading_button_plus: ^3.0.1
  connectivity_plus: ^5.0.2
  connectivity: ^3.0.6
  google_fonts: ^6.2.1
  image_picker: ^1.1.1
  firebase_storage: ^11.7.5
  firebase_app_check: ^0.2.2+7
  firebase_crashlytics: ^3.5.7
  firebase_analytics: ^10.10.7
  dartdoc: ^8.0.8
  build_runner: ^2.4.9
  build_web_compilers: ^4.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/lobablogoblack.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
